- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
and also fixed the configuration
> changed Add Shipping Location to Configuration

- packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
> Changed position of the badge

- packages/Webkul/Admin/src/Config/menu.php
- packages/Webkul/Admin/src/Http/routes.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/configuration/about/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/privacy_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/refund_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/return_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/terms_of_use/index.blade.php
- packages/Webkul/Core/src/Database/Migrations/2019_10_02_134326_create_footer_contents_table.php
- packages/Webkul/Core/src/Models/FooterContent.php
- packages/Webkul/Shipping/src/Config/system.php
- packages/Webkul/Shop/src/Resources/views/home/index.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer_content.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer_credit.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/page_link.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/social_link.blade.php
> New tabs has been added under manage pages

- packages/Webkul/Admin/src/Resources/views/configuration/about/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/privacy_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/refund_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/return_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/terms_of_use/index.blade.php
- packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
- packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
- packages/Webkul/Shipping/src/Config/system.php
> Changed manage pages to custom pages

- packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php
- packages/Webkul/Admin/src/Http/routes.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/about/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/privacy_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/refund_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/return_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/terms_of_use/index.blade.php
- packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
- packages/Webkul/Admin/src/Resources/views/themes/customize.blade.php
- packages/Webkul/Core/src/Database/Migrations/2019_10_02_134326_create_footer_contents_table.php
- packages/Webkul/Core/src/Models/FooterContent.php
- packages/Webkul/Shipping/src/Config/system.php
> tinymce editor has been fixed

- packages/Webkul/Admin/src/Resources/views/configuration/index.blade.php
> manage pages has been fixed

- app/Http/Controllers/PageController.php
- packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php
- packages/Webkul/Admin/src/Resources/views/configuration/about/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/privacy_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/refund_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/return_policy/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/terms_of_use/index.blade.php
- packages/Webkul/Core/src/Models/FooterContent.php
- packages/Webkul/Shop/src/Http/routes.php
- resources/views/pages/store_info.blade.php
> custom pages url has been fix and also populate data in the tabs

- database/seeds/DatabaseSeeder.php
- database/seeds/FooterContentTableSeeder.php
- packages/Webkul/Admin/src/Resources/views/configuration/privacy_policy/index.blade.php
- resources/views/pages/page.blade.php
- resources/views/pages/store_info.blade.php
footer content seeder has been create to manage the store info contents
> footer content seeder has been create to manage the store info contents

- packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/index.blade.php
- packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/sliders/create.blade.php
- packages/Webkul/Admin/src/Resources/views/themes/customize.blade.php
> finishing touch in editors

- packages/Webkul/Shop/src/Resources/views/checkout/onepage/shipping.blade.php
> changes has been fixed

- app/FooterPage.php
- database/migrations/2019_10_14_204555_create_footer_pages_table.php
- packages/Webkul/Admin/src/Config/menu.php
- packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php
- packages/Webkul/Admin/src/Http/Controllers/ThemeManager/ThemeController.php
- packages/Webkul/Admin/src/Http/routes.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/themes/customize.blade.php
- packages/Webkul/Shop/src/Resources/views/checkout/onepage/payment.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/body_section.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer_content.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/page_link.blade.php
> footer page links has been fixed

- database/seeds/ColorPickerTableSeeder.php
- database/seeds/DatabaseSeeder.php
- database/seeds/IconTableSeeder.php
- packages/Webkul/Admin/src/Database/Seeders/DatabaseSeeder.php
I moved the seeder to general seeder. and pls reseed these class: ColorPickerTableSeeder and IconTableSeeder
> fixed seeder issue

- packages/Webkul/Admin/src/Http/Controllers/ThemeManager/ThemeController.php
- packages/Webkul/Admin/src/Resources/views/themes/customize.blade.php
- packages/Webkul/Core/src/Core.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php
> render color from database in the store front

- packages/Webkul/Admin/src/Resources/views/themes/customize.blade.php
> fixed favicon and logo

- packages/Webkul/Admin/src/Http/Controllers/ThemeManager/ThemeController.php
- packages/Webkul/Admin/src/Http/routes.php
- packages/Webkul/Admin/src/Resources/views/themes/customize.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php
> fixed restore default coolors

- packages/Webkul/Admin/src/Http/Controllers/ThemeManager/ThemeController.php
- packages/Webkul/Ui/publishable/assets/css/admin-ui.css
- packages/Webkul/Ui/publishable/assets/css/ui.css
While updating the homepage layout, I discover that it break the site because the appearance section is also link there, so I have to fixed it.
> fixed bugs on updating homepage layout

- app/ColorPicker.php
- database/migrations/2019_10_31_145043_add_hyperlinks_to_color_picker.php
- database/seeds/ColorPickerTableSeeder.php
- packages/Webkul/Admin/src/Http/Controllers/ThemeManager/ThemeController.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/themes/customize.blade.php
- packages/Webkul/Shop/publishable/assets/css/shop.css
- packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php
- public/themes/default/assets/css/shop.css
- public/themes/default/assets/css/style.css
- public/themes/default/assets/images/Checkbox-Checked.svg
- public/themes/default/assets/images/Checkbox.svg
- public/themes/default/assets/images/icon-menu.svg
- public/themes/default/assets/images/icon-search.svg
- public/themes/default/assets/js/shop.js
I fixed bugs on the store front
> fixed bugs on the storefront

- packages/Webkul/Admin/src/Http/Controllers/ThemeManager/ThemeController.php
- packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/session/index.blade.php
- packages/Webkul/Shop/src/Resources/views/customers/signup/index.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php
- public/themes/default/assets/css/shop.css
> fixed storefront facelift part 1

- packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php
- public/themes/default/assets/css/shop.css
- public/themes/default/assets/css/style.css
> fixed storefront colors #ff0000

- public/themes/default/assets/css/style.css
> fixed storefront fields borders to 7

- app/SocialIcon.php
- database/migrations/2019_11_09_045736_create_social_icons_table.php
- database/seeds/DefaultSocialIconTableSeeder.php
- packages/Webkul/Admin/src/Config/menu.php
- packages/Webkul/Admin/src/Database/Seeders/DatabaseSeeder.php
- packages/Webkul/Admin/src/Http/Controllers/ThemeManager/ThemeController.php
- packages/Webkul/Admin/src/Http/routes.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Http/Controllers/SliderController.php
- packages/Webkul/Shop/src/Resources/lang/en/app.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer_content.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer_credit.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/social_link.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/social_theme.blade.php
- storage/framework/views/0264de1b6c97fcf8f48278a064fd6c6c355e49d2.php
- storage/framework/views/03ca2aee1debdd4a40a4b38cf10704b6d7f012d4.php
- storage/framework/views/089378a176f876beb9b11d6f7c1ca1c9e8be01f8.php
- storage/framework/views/141239cf1fac210dacd9dfdde108c9664c016285.php
- storage/framework/views/18f820d8f322f28e8cf5b7df83d54d52d53bdad6.php
- storage/framework/views/1fdf640f94e807b3f2a9b3166cba01633e3aef92.php
- storage/framework/views/527702d9754e36195405952053c30eca1d6317c7.php
- storage/framework/views/545fa3fdd2448045a515d13fe3739ca008c0bacf.php
- storage/framework/views/5bbfc501bd0730e7d740f09cc3368f78eacf7346.php
- storage/framework/views/604a4bdcee93350a33788d7b5b5036a55a99a043.php
- storage/framework/views/88d102149e2d5e369e80d6452b7858df542e6271.php
- storage/framework/views/af05e2b61d679b649b635888f25c67be291aa984.php
- storage/framework/views/afb785caeec61a0f216893774c8215b03eae4013.php
- storage/framework/views/fbe6cc55085fa492a107f42903417ab4b502a275.php
- storage/framework/views/fbf9285207c8d1c5976e60e232838f02abb19706.php
> social icons added and footer credit working also

- packages/Webkul/Attribute/src/Models/AttributeFamily.php
- packages/Webkul/Attribute/src/Models/AttributeGroup.php
- packages/Webkul/Attribute/src/Models/AttributeOption.php
- packages/Webkul/Attribute/src/Models/AttributeOptionTranslation.php
- packages/Webkul/Attribute/src/Models/AttributeTranslation.php
- packages/Webkul/Category/src/Models/Category.php
- packages/Webkul/Category/src/Models/CategoryTranslation.php
- packages/Webkul/Checkout/src/Models/Cart.php
- packages/Webkul/Checkout/src/Models/CartAddress.php
- packages/Webkul/Checkout/src/Models/CartItem.php
- packages/Webkul/Checkout/src/Models/CartPayment.php
- packages/Webkul/Checkout/src/Models/CartShippingRate.php
- packages/Webkul/Core/src/Models/CurrencyExchangeRate.php
- packages/Webkul/Core/src/Models/FooterContent.php
- packages/Webkul/Core/src/Models/Slider.php
- packages/Webkul/Core/src/Models/SubscribersList.php
- packages/Webkul/Core/src/Models/TaxCategory.php
- packages/Webkul/Core/src/Models/TaxMap.php
- packages/Webkul/Core/src/Models/TaxRate.php
- packages/Webkul/Product/src/Models/Product.php
- packages/Webkul/Product/src/Models/ProductAttributeValue.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer_content.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/page_link.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/social_link.blade.php
- storage/framework/views/089378a176f876beb9b11d6f7c1ca1c9e8be01f8.php
- storage/framework/views/afb785caeec61a0f216893774c8215b03eae4013.php
> all input and select width is now 70%

- packages/Webkul/Category/src/Models/Category.php
- packages/Webkul/Product/src/Models/Product.php
- storage/framework/views/af05e2b61d679b649b635888f25c67be291aa984.php
- storage/framework/views/fbe6cc55085fa492a107f42903417ab4b502a275.php
> categories is rendering

- packages/Webkul/Category/src/Models/Category.php
- packages/Webkul/Product/src/Models/Product.php
- storage/framework/views/af05e2b61d679b649b635888f25c67be291aa984.php
- storage/framework/views/fbe6cc55085fa492a107f42903417ab4b502a275.php
Reverts aboutsic/mywebstorespace#97
> Revert "categories is rendering"

- packages/Webkul/Attribute/src/Models/AttributeFamily.php
- packages/Webkul/Attribute/src/Models/AttributeGroup.php
- packages/Webkul/Attribute/src/Models/AttributeOption.php
- packages/Webkul/Attribute/src/Models/AttributeOptionTranslation.php
- packages/Webkul/Attribute/src/Models/AttributeTranslation.php
- packages/Webkul/Category/src/Models/Category.php
- packages/Webkul/Category/src/Models/CategoryTranslation.php
- packages/Webkul/Checkout/src/Models/Cart.php
- packages/Webkul/Checkout/src/Models/CartAddress.php
- packages/Webkul/Checkout/src/Models/CartItem.php
- packages/Webkul/Checkout/src/Models/CartPayment.php
- packages/Webkul/Checkout/src/Models/CartShippingRate.php
- packages/Webkul/Core/src/Models/CurrencyExchangeRate.php
- packages/Webkul/Core/src/Models/FooterContent.php
- packages/Webkul/Core/src/Models/Slider.php
- packages/Webkul/Core/src/Models/SubscribersList.php
- packages/Webkul/Core/src/Models/TaxCategory.php
- packages/Webkul/Core/src/Models/TaxMap.php
- packages/Webkul/Core/src/Models/TaxRate.php
- packages/Webkul/Product/src/Models/Product.php
- packages/Webkul/Product/src/Models/ProductAttributeValue.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer_content.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/page_link.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/social_link.blade.php
- storage/framework/views/089378a176f876beb9b11d6f7c1ca1c9e8be01f8.php
- storage/framework/views/afb785caeec61a0f216893774c8215b03eae4013.php
Reverts aboutsic/mywebstorespace#96
> Revert "all input and select width is now 70%"

- database/seeds/ProductAttributeSeeder.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
- packages/Webkul/Attribute/src/Database/Seeders/DatabaseSeeder.php
- packages/Webkul/Product/src/Repositories/ProductRepository.php
- packages/Webkul/Shop/src/Http/ViewComposers/FeaturedProductListComposer.php
- packages/Webkul/Shop/src/Http/ViewComposers/NewProductListComposer.php
Reverts aboutsic/mywebstorespace#95
> Revert "Attribute fixes"

- packages/Webkul/Attribute/src/Models/AttributeFamily.php
- packages/Webkul/Attribute/src/Models/AttributeGroup.php
- packages/Webkul/Attribute/src/Models/AttributeOption.php
- packages/Webkul/Attribute/src/Models/AttributeOptionTranslation.php
- packages/Webkul/Attribute/src/Models/AttributeTranslation.php
- packages/Webkul/Category/src/Models/Category.php
- packages/Webkul/Category/src/Models/CategoryTranslation.php
- packages/Webkul/Checkout/src/Models/Cart.php
- packages/Webkul/Checkout/src/Models/CartAddress.php
- packages/Webkul/Checkout/src/Models/CartItem.php
- packages/Webkul/Checkout/src/Models/CartPayment.php
- packages/Webkul/Checkout/src/Models/CartShippingRate.php
- packages/Webkul/Core/src/Models/CurrencyExchangeRate.php
- packages/Webkul/Core/src/Models/FooterContent.php
- packages/Webkul/Core/src/Models/Slider.php
- packages/Webkul/Core/src/Models/SubscribersList.php
- packages/Webkul/Core/src/Models/TaxCategory.php
- packages/Webkul/Core/src/Models/TaxMap.php
- packages/Webkul/Core/src/Models/TaxRate.php
- packages/Webkul/Product/src/Models/Product.php
- packages/Webkul/Product/src/Models/ProductAttributeValue.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/footer_content.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/page_link.blade.php
- packages/Webkul/Shop/src/Resources/views/layouts/footer/social_link.blade.php
- storage/framework/views/089378a176f876beb9b11d6f7c1ca1c9e8be01f8.php
- storage/framework/views/afb785caeec61a0f216893774c8215b03eae4013.php
Reverts aboutsic/mywebstorespace#99
> Revert "Revert "all input and select width is now 70%""

- database/seeds/ProductAttributeSeeder.php
- packages/Webkul/Admin/src/Resources/views/catalog/products/edit.blade.php
- packages/Webkul/Attribute/src/Database/Seeders/DatabaseSeeder.php
- packages/Webkul/Product/src/Repositories/ProductRepository.php
- packages/Webkul/Shop/src/Http/ViewComposers/FeaturedProductListComposer.php
- packages/Webkul/Shop/src/Http/ViewComposers/NewProductListComposer.php
Reverts aboutsic/mywebstorespace#102
> Revert "Revert "Attribute fixes""

- packages/Webkul/User/src/Database/Seeders/AdminsTableSeeder.php
- public/themes/default/assets/images/Arrow-Down.svg
- public/themes/default/assets/images/arrow-down.svg
default login has been seeded and its now 
> janeroe@webstore.ng
for email and 
> @hashtag18*
for password
> default login has been seeded

- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/layouts/anonymous-master.blade.php
- packages/Webkul/Admin/src/Resources/views/layouts/nav-top.blade.php
- storage/framework/views/bcd1fbee140f370197638dcd837785c037095ec7.php
- storage/framework/views/c529c7957ef173f3ce6252bfb76a2926f9b92867.php
in storemanager login and navbar, get support has been rename to get help
> get support has been change to get help

- packages/Webkul/Admin/src/DataGrids/ManagePostsDataGrid.php
> fixed little mistake made in post table

- packages/Webkul/Admin/src/DataGrids/ManagePostsDataGrid.php
- packages/Webkul/Admin/src/Resources/views/configuration/blog/index.blade.php
- packages/Webkul/Admin/src/Resources/views/configuration/index.blade.php
- packages/Webkul/Shipping/src/Config/system.php
> fixed left out errors in blog manager

- packages/Webkul/Admin/src/Resources/views/configuration/index.blade.php
- packages/Webkul/Admin/src/Resources/views/settings/channels/edit.blade.php
- packages/Webkul/Core/src/Database/Migrations/2019_12_15_225452_change_status_channels_table.php
- packages/Webkul/Core/src/Http/Controllers/ChannelController.php
- packages/Webkul/Shop/src/Http/Controllers/HomeController.php
- packages/Webkul/Shop/src/Http/routes.php
- packages/Webkul/Shop/src/Resources/views/layouts/master.blade.php
- packages/Webkul/Shop/src/Resources/views/mode/maintenance.blade.php
- storage/framework/views/eefbbd3859bd5d7e956fcabd3c6105ca7e87397c.php
Maintenance mode has been implemented and also fixed bug on create new post in the blog manager
> Maintenance mode has been implemented

- packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php
- resources/views/posts/post.blade.php
Image for the blog post has been resize but it is not 1500 v 600, because it was too large
This mobile view
> Image for the blog post has been resize

- database/seeds/SliderTableSeeder.php
- packages/Webkul/Admin/src/Http/Controllers/ConfigurationController.php
- packages/Webkul/Admin/src/Http/Controllers/ThemeManager/ThemeController.php
- packages/Webkul/Shop/src/Resources/views/mode/maintenance.blade.php
- packages/Webkul/Shop/src/Resources/views/mode/opening-soon.blade.php
- resources/views/posts/post.blade.php
mobile responsiveness has been fixed in store mode and also correction made in slidertableseeder
> mobile responsiveness has been fixed

- packages/Webkul/Admin/src/Http/routes.php
- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/account/payment-method.blade.php
- packages/Webkul/Admin/src/Resources/views/account/select-plan.blade.php
- packages/Webkul/Admin/src/Resources/views/account/side-bar.blade.php
- packages/Webkul/Admin/src/Resources/views/account/subscription.blade.php
- packages/Webkul/User/src/Http/Controllers/AccountController.php
Subscription page has been added and some of the frontend features has been implemented
> Subscription page has been added

- packages/Webkul/Admin/src/Resources/lang/en/app.php
- packages/Webkul/Admin/src/Resources/views/account/payment-method.blade.php
- packages/Webkul/Admin/src/Resources/views/account/subscription.blade.php
fixed typo in the subscription pages
> fixed typo in the subscription pages

- packages/Webkul/Shop/src/Resources/views/mode/maintenance.blade.php
- packages/Webkul/Shop/src/Resources/views/mode/opening-soon.blade.php
Maintenance and Opening soon mode is now 100% mobile responsive
> Maintenance and Opening soon mode is now 100% mobile responsive

- packages/Webkul/Admin/src/Resources/views/sales/invoices/create.blade.php
- packages/Webkul/Admin/src/Resources/views/sales/invoices/view.blade.php
- packages/Webkul/Admin/src/Resources/views/sales/orders/view.blade.php
- packages/Webkul/Admin/src/Resources/views/sales/shipments/create.blade.php
Buttons on sales tab has been moved to bottom per our standard
> Buttons on sales tab has been moved to bottom per our standard

- packages/Webkul/Admin/src/Resources/views/account/side-bar.blade.php
- packages/Webkul/Admin/src/Resources/views/account/webstore.blade.php
> implemented changelog api

- packages/Webkul/Admin/src/Resources/views/settings/channels/index.blade.php
> modified time format
